name: CI

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tag:
        description: 'release标签'
        required: true
        default: 'test'

env:
  WORK_DIR: "QLTools"

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
    #     goos: [linux, windows, darwin]
    #     goarch: ["386", amd64, arm, arm64]
    #     exclude:
    #       - goos: darwin
    #         goarch: arm
    #       - goos: darwin
    #         goarch: "386"
    #   fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '1.19'

      - name: Build binary file
        # env:
        #   GOOS: ${{ matrix.goos }}
        #   GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir dist-$WORK_DIR && cd dist-$WORK_DIR
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          xgo -ldflags='-linkmode external -s -w -extldflags "-static"' -out $WORK_DIR --targets=linux/*,windows/386,windows/amd64,darwin/amd64,darwin/arm64 github.com/${{ github.repository }}
          ls -al ./dist-$WORK_DIR

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist-$WORK_DIR/
