
name: build-go-binary

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [amd64] # 需要打包的架构

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.38
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19 # 可以指定编译使用的 Golang 版本
          ldflags: '-linkmode external -s -w -extldflags "-static"'
          binary_name: "QLTools-${{ matrix.goos }}-${{ matrix.goarch }}" # 可以指定二进制文件的名称
          #extra_files: README.MD ./config/config.yaml # 需要包含的额外文件
          compress_assets: false # 上传前不压缩资源
